ALTER TABLE plan_runs
  ADD COLUMN IF NOT EXISTS weekly_release_version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE plan_run_results
  ADD COLUMN IF NOT EXISTS release_week INTEGER,
  ADD COLUMN IF NOT EXISTS w1 REAL NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS w2 REAL NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS w3 REAL NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS w4 REAL NOT NULL DEFAULT 0;

ALTER TABLE plant_configs
  ALTER COLUMN working_days DROP NOT NULL,
  ALTER COLUMN working_days DROP DEFAULT;