ALTER TABLE api_keys
  ADD COLUMN IF NOT EXISTS consumer TEXT NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS scopes TEXT[] NOT NULL DEFAULT ARRAY['read', 'write'],
  ADD COLUMN IF NOT EXISTS segment_scopes TEXT[] NOT NULL DEFAULT ARRAY['PTMT', 'Plumbing'];