ALTER TABLE plan_runs
  ADD COLUMN IF NOT EXISTS pass2_json JSONB;

ALTER TABLE plan_run_results
  ADD COLUMN IF NOT EXISTS temporary_plan REAL NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cannot_be_made REAL NOT NULL DEFAULT 0;